[tool.poetry]
name = "dj-pr1"
version = "0.1.0"
description = ""
authors = ["Mikhail Postnikov <postnikovmu@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
Django = "^3.0"
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
